version: "3.8"
services:
  api:
    image: kirangowda200/fast_api-api
    # command: uvicorn app.main2:app --host 0.0.0.0 --port 8000 
    ports:
      - "80:8000"
    depends_on:
      - postgres
    # env_file:
    #   - ./.env
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}    
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data  

volumes:
  postgres-db:
